[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "mimey"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = ["version"]
readme = "README.md"
description = "A fast and efficient MIME type and file extension detector implemented in Rust, exposed as a Python package."
license = "MIT"
keywords = ["MIME", "file type detection", "Rust", "Python"]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
module-name = "mimey.mimey"
